### ISSUE TITLE
How would you use showMappleIf for overflowing container?

### ISSUE THREAD

**Issue by L5eoneill** [haldarmahesh/reactjs-mapple-tooltip#9]
Say we only want to use the tooltip if the contents are overflowing the container (say, in a table cell). Can showMappleIf be used to get element.clientWidth < element.scrollWidth ?

That's the one thing we need. Default Bootstrap-style Tooltips (white type, black background, static position relative to hovered element) would be fine; don't need the rest of your very nice component.

**Comment by haldarmahesh** [comment]
@L5eoneill the `showMappleIf` expects valid condition. If you can get the element reference and get  element.clientWidth and element.scrollWidth values, your condition `element.clientWidth < element.scrollWidth` is a valid condition condition which will return boolean.
Let me know if this doesn't answer your query.

For your style requirement of mapple you need to use the `default` mapple, which is black bg and static. You can also configure the style according to your needs. Are you facing any problem in getting your required style of mapple?
